# Generated by Django 5.1.4 on 2025-01-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_age_userprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_smoking',
            field=models.DateField(blank=True, help_text='Date of last smoking', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, help_text="User's title", max_length=255, null=True),
        ),
    ]
