# Generated by Django 5.1.4 on 2024-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the event, e.g., 'Stopped Smoking'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional details about the event', null=True)),
                ('date', models.DateField(help_text='The date of the event')),
            ],
        ),
    ]
