# Generated by Django 5.1.4 on 2025-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_order_product_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Waiting', 'Waiting'), ('Delivered', 'Delivered'), ('Received', 'Received'), ('Settled', 'Settled')], default='Ordered', max_length=10),
        ),
    ]
